theme: jekyll-theme-minimal
title: Cinderstone Studios Installation and Performance Guide
description: A collection of informational guides for installing, optimizing, and running modpacks created by Cinderstone Studios.
